[package]
name = "search"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
elasticlunr-rs = "1"
ammonia = "1"
lazy_static = "1"

errors = { path = "../errors" }
content = { path = "../content" }
