[package]
name = "content"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = "0.11"
serde = "1"
slug = "0.1"
rayon = "1"

errors = { path = "../errors" }
config = { path = "../config" }
utils = { path = "../utils" }
rendering = { path = "../rendering" }
front_matter = { path = "../front_matter" }

[dev-dependencies]
tempdir = "0.3"
toml = "0.4"
globset = "0.3.0"
